-- Create usaw_meet_entries table
CREATE TABLE IF NOT EXISTS public.usaw_meet_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meet_id BIGINT REFERENCES public.usaw_meets(meet_id) ON DELETE CASCADE,
    athlete_id BIGINT REFERENCES public.usaw_lifters(lifter_id) ON DELETE
    SET NULL,
        membership_number TEXT,
        first_name TEXT,
        last_name TEXT,
        state TEXT,
        birth_year INTEGER,
        weightlifting_age INTEGER,
        club TEXT,
        gender TEXT,
        division TEXT,
        weight_class TEXT,
        entry_total NUMERIC,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Add unique constraint to prevent duplicate entries for the same athlete in the same meet
-- Using member_id as the primary deduplication key for entries
CREATE UNIQUE INDEX IF NOT EXISTS idx_usaw_meet_entries_meet_member ON public.usaw_meet_entries(meet_id, member_id);
-- Add index for athlete_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_usaw_meet_entries_athlete_id ON public.usaw_meet_entries(athlete_id);
-- Add index for meet_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_usaw_meet_entries_meet_id ON public.usaw_meet_entries(meet_id);
-- Add comment
COMMENT ON TABLE public.usaw_meet_entries IS 'Stores entry lists for upcoming and past meets scraped from Sport80';