-- Migration: Fix usaw_meets meet_id identity
-- The scraper is failing because meet_id is not auto-generating.
DO $$ BEGIN -- Check if it's already an identity column
IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
        AND table_name = 'usaw_meets'
        AND column_name = 'meet_id'
        AND is_identity = 'YES'
) THEN -- If not identity, check if it has a default sequence
IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
        AND table_name = 'usaw_meets'
        AND column_name = 'meet_id'
        AND column_default LIKE 'nextval%'
) THEN -- No sequence, no identity. Convert to Identity.
-- First, create sequence implicitly via IDENTITY
ALTER TABLE public.usaw_meets
ALTER COLUMN meet_id
ADD GENERATED BY DEFAULT AS IDENTITY;
-- Sync the sequence to the max ID
PERFORM setval(
    pg_get_serial_sequence('public.usaw_meets', 'meet_id'),
    COALESCE(max(meet_id), 0) + 1,
    false
)
FROM public.usaw_meets;
END IF;
END IF;
END $$;