-- Grant permissions for usaw_meet_entries
GRANT ALL ON TABLE public.usaw_meet_entries TO postgres;
GRANT ALL ON TABLE public.usaw_meet_entries TO service_role;
GRANT ALL ON TABLE public.usaw_meet_entries TO anon;
GRANT ALL ON TABLE public.usaw_meet_entries TO authenticated;
-- Also ensure sequence permissions if any (identity column usually handles this but good to be safe)
-- The table uses GENERATED BY DEFAULT AS IDENTITY so sequence is implicit, usually handled by table grants for owners,
-- but for specific roles:
GRANT USAGE,
    SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres;
GRANT USAGE,
    SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT USAGE,
    SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT USAGE,
    SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;